import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Sidebar from "../components/Sidebar/Sidebar";
import Header from "../components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Sidebar is fixed (position: fixed + w-64), so we just render it here */}
        <Sidebar />

        {/* Content wrapper with left margin to account for fixed sidebar */}
        <div className="ml-64">
          {/* Header + Page content */}
          <Header />
          <main className="overflow-y-auto bg-[#F9F9FB] p-6 min-h-screen">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
